import { Link } from "@remix-run/react";
import { Settings } from "lucide-react";

export default function AppPassword() {
  return (
    <article className="mx-32 my-16">
      <h1 className="text-5xl font-bold">
        Getting your App Password on Bluesky
      </h1>
      <h2 className="text-2xl opacity-50 mt-4">
        A short, simple, succinct guide
      </h2>
      <div className="bg-primary/20 rounded-md p-4 mt-8">
        <h3 className="text-xl font-bold">What are app passwords?</h3>
        <p className="mt-4">
          An app password is a unique code generated by the Bluesky platform
          that let third-party apps interact with your Bluesky account without
          giving them your full login credentials.
        </p>
      </div>
      <p className="mt-8">
        Let's see how to get your app password from Bluesky so you can utilize
        our features!
      </p>
      <h2 className="text-xl font-bold mt-8 mb-4">Step 1</h2>
      <p className="ms-4">
        Go to the{" "}
        <Link
          to={"https://bsky.app"}
          target="_blank"
          className="text-primary font-bold"
        >
          Bluesky
        </Link>{" "}
        website or app.
      </p>
      <h2 className="text-xl font-bold mt-8 mb-4">Step 2</h2>
      <p className="ms-4">
        Inside Bluesky, go to <b>Settings</b> (gears icon) and then click on{" "}
        <b>Privacy and security</b> &gt; <b>App Passwords</b>.
      </p>
      <h2 className="text-xl font-bold mt-8 mb-4">Step 3</h2>
      <p className="ms-4">
        Click on <b>Add App Password</b> and enter a unique name for this app
        password, or just click <b>Next</b> to get a randomly generated name.
        <br /> An App Password will be generated for you (it will be a
        16-character string).
      </p>
      <h2 className="text-xl font-bold mt-8 mb-4">Step 4</h2>
      <p className="ms-4">
        Type in or paste the App Password at our Bluesky login page and click on{" "}
        <b>Continue</b>.
      </p>
    </article>
  );
}
