import { Link } from "@remix-run/react";
import { Settings } from "lucide-react";

export default function AppPassword() {
  return (
    <article className="m-16 me-8 col-span-3">
      <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
        Getting your App Password on Bluesky
      </h1>
      <br />
      <p className="text-xl text-muted-foreground">
        A short, simple, succinct guide
      </p>
      <br />
      <div className="border-2 border-primary p-8">
        <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
          What are app passwords?
        </h3>
        <p className="leading-7 [&:not(:first-child)]:mt-6">
          An app password is a unique code generated by the Bluesky platform
          that let third-party apps interact with your Bluesky account without
          giving them your full login credentials.
        </p>
      </div>
      <p className="leading-7 [&:not(:first-child)]:mt-6">
        Let's see how to get your app password from Bluesky so you can utilize
        our features!
      </p>
      <br />
      <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
        Step 1
      </h3>
      <p className="leading-7 [&:not(:first-child)]:mt-6 ms-6">
        Go to the{" "}
        <Link
          to={"https://bsky.app"}
          target="_blank"
          className="text-primary font-bold"
        >
          Bluesky
        </Link>{" "}
        website or app.
      </p>
      <br />
      <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
        Step 2
      </h3>
      <p className="leading-7 [&:not(:first-child)]:mt-6 ms-6">
        Inside Bluesky, go to <b>Settings</b> (gears icon) and then click on{" "}
        <b>Privacy and security</b> &gt; <b>App Passwords</b>.
      </p>
      <br />
      <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
        Step 3
      </h3>
      <p className="leading-7 [&:not(:first-child)]:mt-6 ms-6">
        Click on <b>Add App Password</b> and enter a unique name for this app
        password, or just click <b>Next</b> to get a randomly generated name.
        <br /> An app password will be generated for you (it will be a
        16-character string).
      </p>
      <br />
      <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
        Step 4
      </h3>
      <p className="leading-7 [&:not(:first-child)]:mt-6 ms-6">
        Type in or paste the App Password at our Bluesky login page and click on{" "}
        <b>Continue</b>.
      </p>
    </article>
  );
}
